name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  nextjs:
    name: Next.js – Lint/Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          NEXT_PUBLIC_MLOPS_SERVICE_URL: http://localhost:5001
          NEXT_PUBLIC_APP_URL: http://localhost:3000
        run: npm run build

  flask-tests:
    name: Flask – Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mlops-service
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Run tests
        run: pytest -v
