import pytest
from app import app as flask_app

@pytest.fixture()
def client():
    flask_app.config.update(TESTING=True)
    return flask_app.test_client()

def test_health_ok(client):
    r = client.get("/health")
    assert r.status_code == 200
    data = r.get_json()
    assert data["status"] == "healthy"

def test_metrics_endpoint(client):
    r = client.get("/metrics")
    # Prometheus endpoint should respond with text; presence of "# HELP" is enough
    assert r.status_code == 200
    assert b"# HELP" in r.data

def test_track_happy_path(client):
    payload = {
        "business_id": "demo",
        "response_time_ms": 123,
        "tokens_used": 10,
        "api_cost_usd": 0.001,
        "model_name": "gpt-x",
        "intent_detected": "general",
        "response_type": "text",
        "appointment_requested": False,
        "human_handoff_requested": False,
    }
    r = client.post("/track", json=payload)
    assert r.status_code in (200, 201)
