name: MLOps Service Testing

on:
  push:
    branches: [ main, develop, test-cicd ]
    paths:
      - 'mlops-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mlops-service/**'

jobs:
  test:
    name: Test MLOps Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mlops-service

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Run pytest suite (ok if none yet)
        run: |
          echo "Running pytest…"
          pytest -v || (echo "No tests yet, skipping" && exit 0)
        env:
          FLASK_ENV: testing
          TESTING: true

      # Start Flask without reloader, hit /health, then stop
      - name: Test Flask startup + health
        run: |
          python - <<'PY' &
from app import app
app.run(host='0.0.0.0', port=5001, debug=False)
PY
          SRV_PID=$!
          sleep 4
          curl -fsS http://localhost:5001/health
          kill $SRV_PID || true

      - name: Basic dependency security scan (optional)
        run: |
          pip install safety
          safety check || echo "Warnings found (informational)"
        continue-on-error: true
