name: Next.js Testing

on:
  push:
    branches: [ main, develop, test-cicd ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'next.config.*'
      - 'tailwind.config.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  test:
    name: Test Next.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Lint (optional)
        run: pnpm run lint || echo "No ESLint configured, skipping"

      - name: Type check (optional)
        run: pnpm exec tsc --noEmit || echo "No TS config, skipping"

      - name: Build
        run: pnpm run build

      - name: Verify build output
        run: |
          test -d .next && echo "Build OK" && ls -la .next || (echo "Build failed"; exit 1)
